[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>", "Philip Craig <philipjcraig@gmail.com>"]
name = "object"
version = "0.12.0"
edition = "2018"
description = "A unified interface for parsing object file formats."
keywords = ["object", "loader", "elf", "mach-o", "pe"]
license = "Apache-2.0/MIT"
repository = "https://github.com/gimli-rs/object"
exclude = ["/.coveralls.yml", "/.travis.yml"]

[dependencies]
scroll = { version = "0.9", default-features = false }
uuid = { version = "0.7", default-features = false }
flate2 = { version = "1", optional = true }

[dependencies.goblin]
version = "0.0.22"
default-features = false
features = ["endian_fd", "elf32", "elf64", "mach32", "mach64", "pe32", "pe64", "archive"]

[dependencies.swasm]
version = "0.38.0"
registry = "susytech"
optional = true

[dev-dependencies]
memmap = "0.7"

[features]
std = ["goblin/std"]
compression = ["flate2"]
wasm = ["std", "swasm"]
default = ["std", "compression", "wasm"]
